---

networks:
  monitoring:

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    platform: linux/amd64
    hostname: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    ports:
      - "8080:8080"
    networks:
      - monitoring
    privileged: true
    devices:
      - "/dev/kmsg"
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    ports:
      - "9090:9090"
    networks:
      - monitoring      

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
    ports:
      - 9100:9100
    networks:
      - monitoring      
  
  grafana:
    image: grafana/grafana
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./grafana.yml:/etc/grafana/grafana-datasource-config.yaml
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus