version: '3.8'
services:

  nginx:
    container_name: nginx
    build:
      context: ./  # Caminho para o diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile  # Nome do Dockerfile (opcional se for o padrão "Dockerfile")
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates:/etc/ssl/gosac
    networks:
      - monitoring


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge