global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    scrape_timeout: 8s
    static_configs:
      - targets: 
        - '168.75.66.214:9100'
        - '168.75.76.99:9100'


